export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const INCREASE_ASYNC = "INCREASE_ASYNC";
export const DECREASE_ASYNC = "DECREASE_ASYNC";
