const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: "70vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  tagNo: {
    textAlign: "center",
  },
  tagNoText: {
    fontSize: "5.0rem",
    fontFamily: "Abel",
    fontWeight: 600,
  },
  testKit: {
    minWidth: "100px",
    height: "275px",
  },
  c: {
    position: "absolute",
    top: "190px",
    left: "115px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  c_off: {
    position: "absolute",
    top: "130x",
    left: "115px",
    width: "21px",
    height: "95px",
    transition: "0.5s ease-in-out",
  },
  m: {
    position: "absolute",
    top: "190px",
    left: "160px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  m_off: {
    position: "absolute",
    top: "130px",
    left: "160px",
    width: "21px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  g: {
    position: "absolute",
    top: "190px",
    left: "206px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  g_off: {
    position: "absolute",
    top: "130px",
    left: "206px",
    width: "21px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  cC: {
    position: "absolute",
    top: "330px",
    left: "145px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  cC_off: {
    position: "absolute",
    top: "330px",
    left: "145px",
    width: "21px",
    height: "75px",
    transition: "0.3s ease-in-out",
  },
  t: {
    position: "absolute",
    top: "330px",
    left: "195px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  t_off: {
    position: "absolute",
    top: "330px",
    left: "195px",
    width: "21px",
    height: "75px",
    transition: "0.3s ease-in-out",
  },
  btnReInterpret: {
    position: "absolute",
    top: "450px",
    left: "315px",
  },
  guidePhotoContainer: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "1rem",
  },
  guidePhoto: {
    width: "270px",
    height: "auto",
  },
};
export default styles;
