const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: "70vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  summaryContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  tagNo: {
    textAlign: "center",
  },
  tagNoText: {
    fontSize: "5.0rem",
    fontFamily: "Abel",
    fontWeight: 600,
  },
  testKit: {
    minWidth: "100px",
    height: "275px",
  },
  c: {
    position: "absolute",
    top: "190px",
    left: "115px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  c_off: {
    position: "absolute",
    top: "110x",
    left: "110px",
    width: "32px",
    height: "95px",
    transition: "0.5s ease-in-out",
  },
  m: {
    position: "absolute",
    top: "190px",
    left: "160px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  m_off: {
    position: "absolute",
    top: "190px",
    left: "155px",
    width: "32px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  g: {
    position: "absolute",
    top: "190px",
    left: "206px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  g_off: {
    position: "absolute",
    top: "190px",
    left: "200px",
    width: "32px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  cC: {
    position: "absolute",
    top: "337px",
    left: "145px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  cC_off: {
    position: "absolute",
    top: "320px",
    left: "145px",
    width: "32px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  t: {
    position: "absolute",
    top: "337px",
    left: "195px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  t_off: {
    position: "absolute",
    top: "320px",
    left: "190px",
    width: "32px",
    height: "95px",
    transition: "0.3s ease-in-out",
  },
  btnReInterpret: {
    position: "absolute",
    top: "475px",
    left: "300px",
  },
  guidePhotoContainer: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "1rem",
  },
  guidePhoto: {
    width: "270px",
    height: "auto",
  },
  previewC: {
    position: "absolute",
    top: "165px",
    left: "115px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  previewM: {
    position: "absolute",
    top: "165px",
    left: "160px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  previewG: {
    position: "absolute",
    top: "165px",
    left: "206px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  previewCc: {
    position: "absolute",
    top: "310px",
    left: "145px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  previewT: {
    position: "absolute",
    top: "310px",
    left: "195px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
    transition: "0.5s ease-in-out",
  },
  previewTagNo: {
    position: "absolute",
    top: "640px",
    left: "35px",
    color: "#7f8c8d",
    fontFamily: "Abel",
    fontSize: "17pt",
    fontWeight: 600,
    textShadow: "-0.9px 0.7px 0.7px rgba(255, 255, 255, 1)",
  },
  photoPreviewTagNo: {
    position: "absolute",
    top: "370px",
    left: "25px",
    color: "#636e72",
    fontFamily: "Abel",
    fontSize: "17pt",
    fontWeight: 600,
    textShadow: "-0.9px 0.7px 0.7px rgba(255, 255, 255, 1)",
  },
  summaryPhotoTagNo: {
    position: "absolute",
    top: "775px",
    left: "35px",
    color: "#636e72",
    fontFamily: "Abel",
    fontSize: "17pt",
    fontWeight: 600,
    textShadow: "-0.9px 0.7px 0.7px rgba(255, 255, 255, 1)",
  },
};
export default styles;
