const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: "30vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "1rem",
  },
  randomNo: {
    textAlign: "center",
  },
  randomNoText: {
    fontSize: "5.0rem",
    fontFamily: "Abel",
    fontWeight: 600,
  },
  testKit: {},
  c: {
    position: "absolute",
    top: "180px",
    left: "115px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
  },
  c_off: {
    position: "absolute",
    top: "130x",
    left: "115px",
    width: "21px",
    height: "95px",
  },
  m: {
    position: "absolute",
    top: "180px",
    left: "160px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
  },
  m_off: {
    position: "absolute",
    top: "130px",
    left: "160px",
    width: "21px",
    height: "95px",
  },
  g: {
    position: "absolute",
    top: "180px",
    left: "206px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
  },
  g_off: {
    position: "absolute",
    top: "130px",
    left: "206px",
    width: "21px",
    height: "95px",
  },
  cC: {
    position: "absolute",
    top: "330px",
    left: "145px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
  },
  cC_off: {
    position: "absolute",
    top: "330x",
    left: "145px",
    width: "21px",
    height: "75px",
  },
  t: {
    position: "absolute",
    top: "330px",
    left: "195px",
    backgroundColor: "#6F1E51",
    width: "21px",
    height: "55px",
  },
  t_off: {
    position: "absolute",
    top: "330x",
    left: "195px",
    width: "21px",
    height: "75px",
  },
};
export default styles;
